baseurl: https://susiekim.work/
title: sK
theme: hugo-theme-console
languageCode: en-us
params:
  animateStyle: animated zoomIn fast
  navlinks:
    - name: about/
      url: about/
    - name: posts/
      url: posts/
    - name: photos/
      url: photos/

  titleCutting: yes
