baseurl: https://susie-kim.netlify.app/
title: sK
theme: hugo-theme-console
languageCode: en-us
params:
  animateStyle: animated zoomIn fast
  navlinks:
    - name: posts/
      url: posts/
    - name: photos/
      url: photos/
    - name: about/
      url: about/
  titleCutting: yes
